listing_attrs = [
#Update
    #--Request
    "moxi_works_listing_id", #"String"
    "moxi_works_company_id", #"String"
    "parent_company_id", #"String"
    "underscore_response", #"Boolean"
    #--Response
    "LotSizeAcres", #"Float or null"
    "BathroomsFull", #"Integer or null"
    "BathroomsHalf", #"Integer or null"
    "BathroomsOneQuarter", #"Integer or null"
    "BathroomsPartial", #"Integer or null"
    "BathroomsThreeQuarter", #"Integer or null"
    "BathroomsTotalInteger", #"Integer or null"
    "BathroomsTotal", #"Float or null"
    "BedroomsTotal", #"Integer or null"
    "PublicTitle", #"String or null"
    "PublicRemarks", #"String or null"
    "ModificationTimestamp", #"String"
    "StatusChangeDate", #"String"
    "InternetAddressDisplayYN", #"Boolean or null"
    "DaysOnMarket", #"Integer"
    "ListingContractDate", #"String"
    "CreatedDate", #"String"
    "ElementarySchool", #"String or null"
    "GarageSpaces", #"Integer or null"
    "WaterfrontYN", #"Boolean or null"
    "HighSchool", #"String or null"
    "AssociationFee", #"Integer or null"
    "ListOfficeName", #"String or null"
    "ListPrice", #"Integer or null"
    "ListingID", #"String"
    "ListAgentFullName", #"String"
    "ListAgentUUID", #"String"
    "ListAgentOfficeID", #"String"
    "ListAgentMoxiWorksOfficeID", #"String"
    "SecondaryListAgentFullName", #"String or null"
    "SecondaryListAgentUUID", #"String or null"
    "SchoolDistrict", #"String or null"
    "Address", #"String or null"
    "Address2", #"String or null"
    "City", #"String or null"
    "CountyOrParish", #"String or null"
    "Latitude", #"String or null"
    "Longitude", #"String or null"
    "StateOrProvince", #"String or null"
    "PostalCode", #"String or null"
    "Community", #"String or null"
    "LotSizeSquareFeet", #"Integer or null"
    "InternetEntireListingDisplayYN", #"Boolean"
    "MiddleOrJuniorSchool", #"String or null"
    "ListOfficeAOR", #"String or null"
    "ListOfficeAORArea", #"String or null"
    "PoolYN", #"Boolean or null"
    "PropertyType", #"String or null"
    "TaxAnnualAmount", #"Integer or null"
    "TaxYear", #"Integer or null"
    "SingleStory", #"Boolean or null"
    "LivingArea", #"Integer or null"
    "ViewYN", #"Boolean or null"
    "YearBuilt", #"Integer or null"
    "OnMarket", #"Boolean or null"
    "Status", #"String or null"
    "MoxiWorksListingId", #"String"
    "AgentCreatedListing", #"Boolean"
    "VirtualTourURL", #"String or null"
    "SharedPartnerData", #"Hash"
    "TaxParcelId", #"String or null"
    "ListingURL", #"String or null"
    "PropertyFeatures", #"Array"
    "CompanyListingAttributes", #"Array"
    "OpenHouse", #"Array"
    "ImagesLastModified", #"String or null"
    "ListingImages", #"Array"
    "BuyerCommissionType", #"String or null"
    "BuyerCommissionValue", #"String or null"

#Show
    #--Request
    "moxi_works_listing_id", #"String"
    "moxi_works_company_id", #"String"
    "parent_company_id", #"String"
    "underscore_response", #"Boolean"
    #--Response
    "LotSizeAcres", #"Float or null"
    "BathroomsFull", #"Integer or null"
    "BathroomsHalf", #"Integer or null"
    "BathroomsOneQuarter", #"Integer or null"
    "BathroomsPartial", #"Integer or null"
    "BathroomsThreeQuarter", #"Integer or null"
    "BathroomsTotalInteger", #"Integer or null"
    "BathroomsTotal", #"Float or null"
    "BedroomsTotal", #"Integer or null"
    "PublicTitle", #"String or null"
    "PublicRemarks", #"String or null"
    "ModificationTimestamp", #"String"
    "StatusChangeDate", #"String"
    "InternetAddressDisplayYN", #"Boolean or null"
    "DaysOnMarket", #"Integer"
    "ListingContractDate", #"String"
    "CreatedDate", #"String"
    "ElementarySchool", #"String or null"
    "GarageSpaces", #"Integer or null"
    "WaterfrontYN", #"Boolean or null"
    "HighSchool", #"String or null"
    "AssociationFee", #"Integer or null"
    "ListOfficeName", #"String or null"
    "ListPrice", #"Integer or null"
    "ListingID", #"String"
    "ListAgentFullName", #"String"
    "ListAgentUUID", #"String"
    "ListAgentOfficeID", #"String"
    "ListAgentMoxiWorksOfficeID", #"String"
    "SecondaryListAgentFullName", #"String or null"
    "SecondaryListAgentUUID", #"String or null"
    "SchoolDistrict", #"String or null"
    "Address", #"String or null"
    "Address2", #"String or null"
    "City", #"String or null"
    "CountyOrParish", #"String or null"
    "Latitude", #"String or null"
    "Longitude", #"String or null"
    "StateOrProvince", #"String or null"
    "PostalCode", #"String or null"
    "Community", #"String or null"
    "LotSizeSquareFeet", #"Integer or null"
    "InternetEntireListingDisplayYN", #"Boolean"
    "MiddleOrJuniorSchool", #"String or null"
    "ListOfficeAOR", #"String or null"
    "ListOfficeAORArea", #"String or null"
    "PoolYN", #"Boolean or null"
    "PropertyType", #"String or null"
    "TaxAnnualAmount", #"Integer or null"
    "TaxYear", #"Integer or null"
    "SingleStory", #"Boolean or null"
    "LivingArea", #"Integer or null"
    "ViewYN", #"Boolean or null"
    "YearBuilt", #"Integer or null"
    "OnMarket", #"Boolean or null"
    "Status", #"String or null"
    "MoxiWorksListingId", #"String"
    "AgentCreatedListing", #"Boolean"
    "VirtualTourURL", #"String or null"
    "SharedPartnerData", #"Hash"
    "TaxParcelId", #"String or null"
    "ListingURL", #"String or null"
    "PropertyFeatures", #"Array"
    "CompanyListingAttributes", #"Array"
    "OpenHouse", #"Array"
    "ImagesLastModified", #"String or null"
    "ListingImages", #"Array"
    "BuyerCommissionType", #"String or null"
    "BuyerCommissionValue", #"String or null"

#Index
    #--Request
    "moxi_works_company_id", #"String"
    "parent_company_id", #"String"
    "updated_since", #"Integer"
    "agent_uuid", #"String"
    "moxi_works_agent_id", #"String"
    "source_agent_id", #"String"
    "moxi_works_office_id", #"String"
    "last_moxi_works_listing_id", #"String"
    "shared_partner_data_updated_since", #"Integer"
    "market_status", #"String"
    "property_types", #"String"
    "only_agent_created", #"Boolean"
    "coming_soon", #"Boolean"
    "underscore_response", #"Boolean"
    "timestamps_only", #"Boolean"
    #--Response
    "FinalPage", #"Boolean"
    "Listings" #"Array"
]

listing_attrs.each do |attr_title|
    AssociatedAttr.find_or_create_by(attr_title: attr_title) do |attr|
      # Set other attributes if necessary, for example:
      attr.request_type = {}
      attr.associated_endpoint = {}
    end
  end